#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Sep  9 16:29:23 2019

@author: gustavo
"""
import pygame

'''Setup variables'''
size = (616,616) #Window size
block_size = 40 #Block size

#RGB for colors
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
GREEN = (0, 255, 0)
RED = (255, 0, 0)

'''Initialize pygame'''
pygame.init()

'''Activate the window display'''
screen = pygame.display.set_mode(size)
pygame.display.set_caption("Dijkstra's algorithm")

done = False #Control boolean variables

'''Activate clock'''
#Manages the speed of updates in the window
clock = pygame.time.Clock()

'''Grid setup'''
width=15
height=15
margin=1

'''Game loop'''
#Al the Dijkstra graphical simulation goes inside this while loop
while not done:
    #This section allows the window to be closed
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            done = True
    
    screen.fill(WHITE) #Window background color
    
    for column in range(0, 800, width):
        for row in range(0, 800, height):
            pygame.draw.rect(screen, BLACK, [column,row,width,height], 1)
    
    #Example of movements
    #To select a given square, it needs to be colored, for example:
    #The next line chooses the first square from upper left corner
    pygame.draw.rect(screen, RED, [ 1, 1, width - 1, height - 1])
    #The next line chooses the square( 25, 25)
    pygame.draw.rect(screen, RED, [15*25 , 15*(25), width -1 , height - 1])
    #The next line chooses the square(39,10)
    pygame.draw.rect(screen, RED, [15*39 , 15*10 , width - 1, height - 1])
        
    pygame.display.flip() #Actualize a change in the window (important)
    
    clock.tick(60) #60 fps only

#Close the window
pygame.quit()